package com.ihy2ln.weaverse.feature.roleplay.textgame

/** The 69 V2-Varied Codex card fronts bundled with the Adams Haven prototype. */
fun adamsHavenCardCatalog(): List<TextGameCollectibleCard> = listOf(
    collectible("characters", "amara-the-alluring-empress", "Amara, the Alluring Empress"),
    collectible("characters", "carmen-delga", "Carmen Delga"),
    collectible("characters", "clarity-lockhart", "Clarity Lockhart"),
    collectible("characters", "daisy-bonfire-wildheart", "Daisy “Bonfire” Wildheart"),
    collectible("characters", "dr-elena-valera", "Dr. Elena Valera"),
    collectible("characters", "dr-zephyrine-zeph-solmara", "Dr. Zephyrine “Zeph” Solmara"),
    collectible("characters", "elara-vellum", "Elara Vellum"),
    collectible("characters", "elowen-moonwhisper", "Elowen Moonwhisper"),
    collectible("characters", "ghislaine-dedoldia", "Ghislaine Dedoldia"),
    collectible("characters", "handler-zara-knox", "Handler Zara Knox"),
    collectible("characters", "helda-frostmane", "Helda Frostmane"),
    collectible("characters", "isekai-incubus-system", "Isekai Incubus System"),
    collectible("characters", "jasmine-kaela-buttacks", "Jasmine Kaela Buttacks"),
    collectible("characters", "jenna-reyes", "Jenna Reyes"),
    collectible("characters", "ji-hyun", "Ji-Hyun"),
    collectible("characters", "jman", "JMan"),
    collectible("characters", "john-civ", "John Civ"),
    collectible("characters", "john-gaming", "John Gaming"),
    collectible("characters", "john-hero", "John Hero"),
    collectible("characters", "john-isekai", "John Isekai"),
    collectible("characters", "john-michael-doe", "John Michael Doe"),
    collectible("characters", "john-z", "John Z"),
    collectible("characters", "kaela-stormfang", "Kaela Stormfang"),
    collectible("characters", "kalani-lani-kealoha", "Kalani “Lani” Kealoha"),
    collectible("characters", "kimberly-stacy", "Kimberly Stacy"),
    collectible("characters", "lena-ziegler", "Lena Ziegler"),
    collectible("characters", "lyra-thornbrook", "Lyra Thornbrook"),
    collectible("characters", "mara-thorne-draven", "Mara Thorne-Draven"),
    collectible("characters", "mary-jane", "Mary Jane"),
    collectible("characters", "mira-sylva", "Mira Sylva"),
    collectible("characters", "mrs-delgado", "Mrs. Delgado"),
    collectible("characters", "ruinous-maw", "Ruinous Maw"),
    collectible("characters", "soo-yeon", "Soo-Yeon"),
    collectible("characters", "theresa-tessa-rivera", "Theresa “Tessa” Rivera"),
    collectible("characters", "vera-ironbough", "Vera Ironbough"),
    collectible("characters", "virginia-puffton", "Virginia Puffton"),
    collectible("characters", "wah-embrace-enhanced-male-breeding-relationship-advancement-control-engi", "WAH Embrace Control Engine"),
    collectible("characters", "yumi-silken-guard-ishihara", "Yumi “Silken Guard” Ishihara"),
    collectible("locations", "adams-haven", "Adams Haven"),
    collectible("locations", "afm-bunkers-rooms", "AFM Bunkers & Rooms"),
    collectible("locations", "aqualuria", "Aqualuria"),
    collectible("locations", "arcanis", "Arcanis"),
    collectible("locations", "california", "California"),
    collectible("locations", "elysara", "Elysara"),
    collectible("locations", "elysium-vale", "Elysium Vale"),
    collectible("locations", "fixer-upper", "Fixer Upper"),
    collectible("locations", "heroica", "Heroica"),
    collectible("locations", "los-angeles-asteroid", "Los Angeles Asteroid"),
    collectible("locations", "major-cities-of-mythoria", "Major Cities of Mythoria"),
    collectible("locations", "major-continents-of-elysium-vale", "Major Continents of Elysium Vale"),
    collectible("locations", "mythoria", "Mythoria"),
    collectible("locations", "nexara-prime", "Nexara Prime"),
    collectible("locations", "pacific-bastion-coastal-residence", "Pacific Bastion Coastal Residence"),
    collectible("locations", "serenity-atoll", "Serenity Atoll"),
    collectible("locations", "silverbrook-adventure-guild", "Silverbrook Adventure Guild"),
    collectible("locations", "silverbrook-city", "Silverbrook City"),
    collectible("locations", "silverwood-forest", "Silverwood Forest"),
    collectible("locations", "starter-base", "Starter Base"),
    collectible("locations", "the-argent-bourse", "The Argent Bourse"),
    collectible("locations", "the-frosted-mug-inn", "The Frosted Mug Inn"),
    collectible("locations", "the-harmonized-expanse", "The Harmonized Expanse"),
    collectible("locations", "the-sandcastle", "The Sandcastle"),
    collectible("locations", "ucla-neo-campus-interactive-media-digital-narrative-complex", "UCLA Neo-Campus Interactive Media Complex"),
    collectible("locations", "ucla", "UCLA"),
    collectible("locations", "usa", "USA"),
    collectible("locations", "veridian", "Veridian"),
    collectible("objects", "celestium-clone-bodies", "Celestium Clone Bodies"),
    collectible("objects", "celestium", "Celestium"),
    collectible("objects", "life-technology-e-xperience-ltx", "Life Technology eXperience (LTX)"),
)

private fun collectible(category: String, slug: String, title: String) = TextGameCollectibleCard(
    id = "$category/$slug",
    title = title,
    category = category,
    mediaId = "adams-haven-$category-$slug",
    artAssetPath = "images/adams_haven/$category/$slug.png",
)
