package com.ihy2ln.weaverse.feature.roleplay.textgame

const val ADAMS_HAVEN_GAME_ID = "adams_haven_first_draw"

/** Bundled, network-free proof game for the reusable Text Game runtime. */
fun adamsHavenTutorial(): TextGameDefinition = TextGameDefinition(
    id = ADAMS_HAVEN_GAME_ID,
    schemaVersion = 4,
    title = "Adams Haven: The First Draw",
    subtitle = "A branching card-RPG prologue",
    startNodeId = "crossroads",
    nodes = listOf(
        TextGameNode(
            id = "crossroads",
            type = TextGameNodeType.Hub,
            title = "The Haven Crossroads",
            prose = "I stand on the dirt road at the center of my new Haven. The small shack rests behind me, the unmaintained field lies to one side, and the dark road toward the first dungeon waits ahead. I choose what my day becomes.",
            proseVariants = listOf(
                "I reach the four-way road under a rain-thinned dawn. My shack, the fallow Farm, the empty Town lot, and the dungeon route each demand a different kind of work.",
                "I wake to cart tracks crossing the Haven road where none existed last night. From the center I can investigate Town, reclaim the Farm, return Home, or follow the marks toward the dungeon.",
                "I stand at the four-way road while silver mist lifts from the grass. Smoke curls from my shack, crows circle the Farm, and a distant bell answers from the dungeon road.",
                "I arrive at the Haven crossroads with the card case warm against my side. The quiet Town lot, ruined field, small House, and dangerous road leave the first move to me.",
                "I step into bright morning at the center of Haven. One road promises shelter, one labor, one community, and one a fight; I decide which promise matters first.",
                "I find a sealed letter pinned where the four dirt roads meet. Before I open it, I can secure Home, inspect the Farm, walk the Town lot, or test the dungeon route.",
            ),
            sceneAssetType = "crossroads",
            sceneMediaId = "adams-haven-locations-adams-haven",
            bundledSceneAssetPath = "images/adams_haven/locations/adams-haven.png",
            choices = listOf(
                TextGameChoice("to_dungeon", "I follow the dungeon road to the mission board", "shack"),
                TextGameChoice("to_farm", "I inspect the unmaintained Farm", "farm"),
                TextGameChoice("to_town", "I visit the Town lot", "town"),
                TextGameChoice("to_house", "I enter the small shack", "home"),
                TextGameChoice(
                    "to_mission",
                    "I accept the first real mission",
                    "contract",
                    condition = TextGameCondition(
                        requiredFlags = listOf("gacha_tutorial_complete", "home_secured"),
                    ),
                ),
            ),
            hotspots = listOf(
                TextGameHotspot("dungeon", "Dungeon", "to_dungeon", .82f, .55f),
                TextGameHotspot("farm", "Farm", "to_farm", .18f, .48f),
                TextGameHotspot("town", "Town", "to_town", .55f, .32f),
                TextGameHotspot("house", "House", "to_house", .50f, .70f),
            ),
        ),
        TextGameNode(
            id = "shack",
            type = TextGameNodeType.MissionBoard,
            title = "The Dungeon Mission Board",
            prose = "I stop beneath the lanterns at the dungeon road's mission board. Fresh contracts wait under wax seals, and I decide which danger becomes my next story.",
            proseVariants = listOf(
                "I reach a rain-dark board where new contracts knock softly against their brass pins. Each notice promises a different route below Haven.",
                "I step beneath the mission awning as a courier fixes fresh requests to the board. Ink, monster spoor, and promised coin compete for my attention.",
                "I find the dungeon board crowded with maps that were not here yesterday. I read the available work before I commit my party.",
                "I arrive while the mission keeper lights six small lanterns over the newest contracts. Some requests offer coin, others answers, and none offer safety.",
                "I brush road dust from my coat and face the board at the dungeon gate. The case at my side warms as if it already favors one sealed mission.",
                "I enter the contract shelter to the sound of distant stone shifting underground. New work waits, and I choose how this expedition begins.",
            ),
            sceneAssetType = "dungeon",
            sceneMediaId = "adams-haven-locations-silverwood-forest",
            bundledSceneAssetPath = "images/adams_haven/locations/silverwood-forest.png",
            missionDestinationNodeId = "summoning",
            missionRepeatDestinationNodeId = "contract",
            missionRepeatRequiredFlag = "gacha_tutorial_complete",
            choices = listOf(
                TextGameChoice(
                    id = "mission_board_crossroads",
                    label = "I return to the Haven Crossroads",
                    destinationNodeId = "crossroads",
                ),
            ),
        ),
        TextGameNode(
            id = "summoning",
            type = TextGameNodeType.Narrative,
            title = "The First Summoning",
            prose = "I call through the case. Kaela Stormfang answers in cold wind, and Ghislaine Dedoldia arrives in obedient fire. I choose who takes my first order.",
            sceneMediaId = "adams-haven-characters-amara-the-alluring-empress",
            bundledSceneAssetPath = "images/adams_haven/characters/amara-the-alluring-empress.png",
            choices = listOf(
                choice("choose_kestrel", "I ask Kaela to lead", "road", flag = "kestrel_leads", companion = "kestrel"),
                choice("choose_sable", "I ask Ghislaine to scout", "road", flag = "sable_scouts", companion = "sable"),
                choice("choose_together", "I ask them to choose our formation together", "road", flag = "balanced_formation", companion = "kestrel"),
            ),
        ),
        TextGameNode(
            id = "road",
            type = TextGameNodeType.Narrative,
            title = "Glassroot Road",
            prose = "Blue roots shine beneath my boots. Ahead, Warden raises a draining lantern while Stinger prepares to mend every wound my cards make.",
            sceneAssetType = "dungeon",
            sceneMediaId = "adams-haven-locations-silverwood-forest",
            bundledSceneAssetPath = "images/adams_haven/locations/silverwood-forest.png",
            choices = listOf(
                choice("burst_plan", "I prepare a burst attack", "battle", flag = "burst_plan"),
                choice("transfer_plan", "I plan an energy transfer", "battle", flag = "transfer_plan"),
                choice("reserve_plan", "I bank our strength for the enemy intent", "battle", flag = "reserve_plan"),
            ),
        ),
        TextGameNode(
            id = "battle",
            type = TextGameNodeType.Battle,
            title = "The Three in the Dark",
            prose = "I choose a living target, command affordable cards from our shared hand, and end the turn when my formation is spent. Every enemy intent remains visible to me.",
            sceneAssetType = "battle",
            sceneMediaId = "adams-haven-locations-silverbrook-adventure-guild",
            bundledSceneAssetPath = "images/adams_haven/locations/silverbrook-adventure-guild.png",
            encounterId = "first_encounter",
            victoryNodeId = "reward",
            defeatNodeId = "defeat",
            victoryFlag = "first_battle_won",
            victoryEffects = listOf(TextGameEffect(seedsDelta = 1, materialsDelta = 2)),
        ),
        TextGameNode(
            id = "reward",
            type = TextGameNodeType.Reward,
            title = "The Card That Remembers",
            prose = "Three cards rise from the broken lantern. The draw follows the case's seed, but I choose which promise becomes permanent.",
            sceneMediaId = "adams-haven-objects-celestium",
            bundledSceneAssetPath = "images/adams_haven/objects/celestium.png",
            rewardDestinationNodeId = "gacha",
        ),
        TextGameNode(
            id = "gacha",
            type = TextGameNodeType.Gacha,
            title = "The First Summoning Draw",
            prose = "I carry the first permanent card back to the Haven crossroads. The case opens a local summoning tutorial: two seeded draws bring new allies into my roster before the first real mission.",
            sceneMediaId = "adams-haven-objects-celestium",
            bundledSceneAssetPath = "images/adams_haven/objects/celestium.png",
            choices = listOf(
                TextGameChoice(
                    id = "continue_after_gacha",
                    label = "I return to the Haven Crossroads",
                    destinationNodeId = "crossroads",
                    condition = TextGameCondition(requiredFlag = "gacha_tutorial_complete"),
                ),
            ),
        ),
        TextGameNode(
            id = "farm",
            type = TextGameNodeType.Hub,
            title = "The Plot Behind the Shack",
            prose = "I find one open bed behind the shack. I plant what the battle gives me now; another expedition will advance the crop before I harvest it.",
            sceneAssetType = "farm",
            sceneMediaId = "adams-haven-locations-fixer-upper",
            bundledSceneAssetPath = "images/adams_haven/locations/fixer-upper.png",
            sceneMotionMediaId = "adams-haven-motion-farm",
            bundledSceneMotionAssetPath = "videos/adams_haven/farm.mp4",
            choices = listOf(
                TextGameChoice(
                    id = "clear_plot",
                    label = "I clear one plot (+1 Farm progress)",
                    destinationNodeId = "farm",
                    condition = TextGameCondition(forbiddenFlag = "farm_cleared"),
                    effects = listOf(TextGameEffect(setFlag = "farm_cleared")),
                ),
                TextGameChoice(
                    id = "upgrade_farm_l2",
                    label = "I improve the first plot — 4 coins, 1 material",
                    destinationNodeId = "farm",
                    condition = TextGameCondition(requiredFlag = "farm_cleared", forbiddenFlag = "farm_l2", minimumCoins = 4, minimumMaterials = 1),
                    effects = listOf(TextGameEffect(coinsDelta = -4, materialsDelta = -1, farmLevelDelta = 1, setFlag = "farm_l2")),
                ),
                TextGameChoice(
                    id = "upgrade_farm_l3",
                    label = "I add a second bed — 8 coins, 3 materials",
                    destinationNodeId = "farm",
                    condition = TextGameCondition(requiredFlag = "farm_l2", forbiddenFlag = "farm_l3", minimumCoins = 8, minimumMaterials = 3),
                    effects = listOf(TextGameEffect(coinsDelta = -8, materialsDelta = -3, farmLevelDelta = 1, setFlag = "farm_l3")),
                ),
                TextGameChoice(
                    id = "plant",
                    label = "I plant one haven seed",
                    destinationNodeId = "farm",
                    condition = TextGameCondition(requiredFlag = "farm_cleared", forbiddenFlag = "crop_planted", minimumSeeds = 1),
                    effects = listOf(TextGameEffect(seedsDelta = -1, setFlag = "crop_planted")),
                ),
                TextGameChoice(
                    id = "tend_beds",
                    label = "I tend the improved beds (+1 produce)",
                    destinationNodeId = "farm",
                    condition = TextGameCondition(requiredFlag = "farm_l2"),
                    effects = listOf(TextGameEffect(harvestDelta = 1)),
                ),
                TextGameChoice("farm_crossroads", "I return to the Haven Crossroads", "crossroads"),
                TextGameChoice(
                    id = "to_town",
                    label = "I leave the crop to grow and follow the lights into Town",
                    destinationNodeId = "town",
                    condition = TextGameCondition(requiredFlag = "crop_planted"),
                ),
            ),
        ),
        TextGameNode(
            id = "town",
            type = TextGameNodeType.Hub,
            title = "The First Town Lot",
            prose = "I carry dungeon coin and salvaged ore into Silverbrook. A builder can turn both into a Deck Hall—the first permanent service my Haven needs.",
            sceneAssetType = "town",
            sceneMediaId = "adams-haven-locations-silverbrook-city",
            bundledSceneAssetPath = "images/adams_haven/locations/silverbrook-city.png",
            sceneMotionMediaId = "adams-haven-motion-town",
            bundledSceneMotionAssetPath = "videos/adams_haven/town.mp4",
            choices = listOf(
                TextGameChoice(
                    id = "build_deck_hall",
                    label = "I build the Deck Hall — 5 coins, 2 materials",
                    destinationNodeId = "home",
                    condition = TextGameCondition(minimumCoins = 5, minimumMaterials = 2, forbiddenFlag = "town_l2"),
                    effects = listOf(
                        TextGameEffect(coinsDelta = -5, materialsDelta = -2, townLevelDelta = 1, setFlag = "town_l2"),
                        TextGameEffect(setFlag = "deck_hall_built"),
                    ),
                ),
                TextGameChoice(
                    id = "buy_supplies",
                    label = "I buy field supplies — 2 coins (+1 seed)",
                    destinationNodeId = "town",
                    condition = TextGameCondition(requiredFlag = "town_l2", minimumCoins = 2),
                    effects = listOf(TextGameEffect(coinsDelta = -2, seedsDelta = 1, setFlag = "bought_supplies")),
                ),
                TextGameChoice(
                    id = "buy_seed",
                    label = "I buy one loose seed — 2 coins",
                    destinationNodeId = "town",
                    condition = TextGameCondition(requiredFlag = "town_l2", minimumCoins = 2),
                    effects = listOf(TextGameEffect(coinsDelta = -2, seedsDelta = 1)),
                ),
                TextGameChoice("town_house", "I enter the House", "home"),
                TextGameChoice("town_crossroads", "I return to the Haven Crossroads", "crossroads"),
                TextGameChoice(
                    id = "town_l3",
                    label = "I expand Town with the Guild Hall — 8 coins, 4 materials",
                    destinationNodeId = "town",
                    condition = TextGameCondition(requiredFlag = "town_l2", forbiddenFlag = "town_l3", minimumCoins = 8, minimumMaterials = 4),
                    effects = listOf(TextGameEffect(coinsDelta = -8, materialsDelta = -4, townLevelDelta = 1, setFlag = "town_l3")),
                ),
                TextGameChoice(
                    id = "town_l4",
                    label = "I expand Town with a Workshop — 12 coins, 6 materials",
                    destinationNodeId = "town",
                    condition = TextGameCondition(requiredFlag = "town_l3", forbiddenFlag = "town_l4", minimumCoins = 12, minimumMaterials = 6),
                    effects = listOf(TextGameEffect(coinsDelta = -12, materialsDelta = -6, townLevelDelta = 1, setFlag = "town_l4")),
                ),
                TextGameChoice(
                    id = "town_l5",
                    label = "I establish the Town — 18 coins, 9 materials",
                    destinationNodeId = "town",
                    condition = TextGameCondition(requiredFlag = "town_l4", forbiddenFlag = "town_l5", minimumCoins = 18, minimumMaterials = 9),
                    effects = listOf(TextGameEffect(coinsDelta = -18, materialsDelta = -9, townLevelDelta = 1, setFlag = "town_l5")),
                ),
            ),
        ),
        TextGameNode(
            id = "home",
            type = TextGameNodeType.Hub,
            title = "Home in the Third Space",
            prose = "I set my permanent card inside the case and study the repaired expedition board. Home restores my footing and lets me turn shelter into protection for the next fight.",
            sceneMediaId = "adams-haven-locations-adams-haven",
            bundledSceneAssetPath = "images/adams_haven/locations/adams-haven.png",
            sceneMotionMediaId = "adams-haven-motion-home",
            bundledSceneMotionAssetPath = "videos/adams_haven/home.mp4",
            choices = listOf(
                TextGameChoice(
                    id = "rest_home",
                    label = "I rest until morning (restore health)",
                    destinationNodeId = "home",
                    effects = listOf(TextGameEffect(healthDelta = 99)),
                ),
                TextGameChoice(
                    id = "upgrade_house_l2",
                    label = "I repair the shack — 4 coins, 1 material",
                    destinationNodeId = "home",
                    condition = TextGameCondition(forbiddenFlag = "house_l2", minimumCoins = 4, minimumMaterials = 1),
                    effects = listOf(TextGameEffect(coinsDelta = -4, materialsDelta = -1, homeLevelDelta = 1, setFlag = "house_l2")),
                ),
                TextGameChoice(
                    id = "upgrade_house_l3",
                    label = "I build the kitchen and workshop — 7 coins, 3 materials",
                    destinationNodeId = "home",
                    condition = TextGameCondition(requiredFlag = "house_l2", forbiddenFlag = "house_l3", minimumCoins = 7, minimumMaterials = 3),
                    effects = listOf(TextGameEffect(coinsDelta = -7, materialsDelta = -3, homeLevelDelta = 1, setFlag = "house_l3")),
                ),
                TextGameChoice(
                    id = "upgrade_house_l4",
                    label = "I expand the shack — 11 coins, 5 materials",
                    destinationNodeId = "home",
                    condition = TextGameCondition(requiredFlag = "house_l3", forbiddenFlag = "house_l4", minimumCoins = 11, minimumMaterials = 5),
                    effects = listOf(TextGameEffect(coinsDelta = -11, materialsDelta = -5, homeLevelDelta = 1, setFlag = "house_l4")),
                ),
                TextGameChoice(
                    id = "upgrade_house_l5",
                    label = "I raise the manor — 16 coins, 8 materials",
                    destinationNodeId = "home",
                    condition = TextGameCondition(requiredFlag = "house_l4", forbiddenFlag = "house_l5", minimumCoins = 16, minimumMaterials = 8),
                    effects = listOf(TextGameEffect(coinsDelta = -16, materialsDelta = -8, homeLevelDelta = 1, setFlag = "house_l5")),
                ),
                TextGameChoice(
                    id = "prepare_home",
                    label = "I secure the shack (+3 guard for the next battle)",
                    destinationNodeId = "home",
                    condition = TextGameCondition(requiredFlag = "deck_hall_built", forbiddenFlag = "home_secured"),
                    effects = listOf(TextGameEffect(preparedGuardDelta = 3, homeLevelDelta = 1, setFlag = "home_secured")),
                ),
                TextGameChoice(
                    id = "take_contract",
                    label = "I accept the Silverwood contract",
                    destinationNodeId = "contract",
                    condition = TextGameCondition(requiredFlags = listOf("deck_hall_built", "home_secured")),
                    effects = listOf(TextGameEffect(setFlag = "silverwood_contract")),
                ),
                TextGameChoice("home_town", "I walk to the Town lot", "town"),
                TextGameChoice("home_farm", "I walk to the Farm", "farm"),
                TextGameChoice("home_crossroads", "I return to the Haven Crossroads", "crossroads"),
            ),
        ),
        TextGameNode(
            id = "contract",
            type = TextGameNodeType.Narrative,
            title = "The Silverwood Contract",
            prose = "I find a glassroot sentinel cornering a creature called the Ruinous Maw. The contract pays for restraint, but my card case hums for a decisive draw.",
            sceneAssetType = "dungeon",
            sceneMediaId = "adams-haven-locations-silverwood-forest",
            bundledSceneAssetPath = "images/adams_haven/locations/silverwood-forest.png",
            choices = listOf(
                choice("protect_the_road", "I protect the road and challenge both threats", "contract_battle", flag = "protected_road"),
                choice("follow_the_maw", "I follow the Maw's trail before striking", "contract_battle", flag = "followed_maw"),
                choice("read_the_field", "I study both threats before I commit the party", "contract_battle", flag = "read_the_field"),
            ),
        ),
        TextGameNode(
            id = "contract_battle",
            type = TextGameNodeType.Battle,
            title = "Glassroot Reckoning",
            prose = "The shelter I prepare absorbs the opening pressure. My permanent card lends the party Haven Guard, and I decide whether to spend recovered SP or rely on our shared combo.",
            sceneAssetType = "battle",
            sceneMediaId = "adams-haven-characters-ruinous-maw",
            bundledSceneAssetPath = "images/adams_haven/characters/ruinous-maw.png",
            encounterId = "silverwood_contract",
            victoryNodeId = "contract_reward",
            defeatNodeId = "defeat",
            victoryCoins = 5,
            victorySp = 1,
            victoryFlag = "silverwood_won",
            victoryEffects = listOf(TextGameEffect(materialsDelta = 3, seedsDelta = 1, cropGrowthDelta = 1)),
        ),
        TextGameNode(
            id = "contract_reward",
            type = TextGameNodeType.Reward,
            title = "A Second Name in the Case",
            prose = "The glassroot releases three more character cards. I choose one, while the battle's passage of time ripens the lanternroot behind my shack.",
            sceneMediaId = "adams-haven-objects-celestium-clone-bodies",
            bundledSceneAssetPath = "images/adams_haven/objects/celestium-clone-bodies.png",
            rewardDestinationNodeId = "return_farm",
        ),
        TextGameNode(
            id = "return_farm",
            type = TextGameNodeType.Hub,
            title = "The First Harvest",
            prose = "I return after the contract and find the lanternroot mature. Farm work now turns battle time into food, and the kitchen turns food into preparation.",
            sceneAssetType = "farm",
            sceneMediaId = "adams-haven-locations-fixer-upper",
            bundledSceneAssetPath = "images/adams_haven/locations/fixer-upper.png",
            sceneMotionMediaId = "adams-haven-motion-farm",
            bundledSceneMotionAssetPath = "videos/adams_haven/farm.mp4",
            choices = listOf(
                TextGameChoice(
                    id = "harvest",
                    label = "I harvest the mature lanternroot (+2 produce)",
                    destinationNodeId = "return_farm",
                    condition = TextGameCondition(requiredFlags = listOf("silverwood_won", "crop_planted"), forbiddenFlag = "crop_harvested", minimumCropGrowth = 1),
                    effects = listOf(TextGameEffect(harvestDelta = 2, cropGrowthDelta = -1, farmLevelDelta = 1, setFlag = "crop_harvested")),
                ),
                TextGameChoice(
                    id = "cook_dish",
                    label = "I cook lantern stew — 1 produce",
                    destinationNodeId = "return_farm",
                    condition = TextGameCondition(requiredFlag = "crop_harvested", forbiddenFlag = "dish_cooked", minimumHarvest = 1),
                    effects = listOf(TextGameEffect(harvestDelta = -1, dishesDelta = 1, setFlag = "dish_cooked")),
                ),
                TextGameChoice(
                    id = "carry_to_market",
                    label = "I carry the surplus to Town",
                    destinationNodeId = "return_town",
                    condition = TextGameCondition(requiredFlag = "dish_cooked", minimumHarvest = 1),
                ),
            ),
        ),
        TextGameNode(
            id = "return_town",
            type = TextGameNodeType.Hub,
            title = "Market and Deck Hall",
            prose = "I sell my surplus through the Market, then combine that coin with dungeon ore. Town turns the Farm and dungeon outputs into lasting capability.",
            sceneAssetType = "town",
            sceneMediaId = "adams-haven-locations-silverbrook-city",
            bundledSceneAssetPath = "images/adams_haven/locations/silverbrook-city.png",
            choices = listOf(
                TextGameChoice(
                    id = "sell_produce",
                    label = "I sell one produce (+3 coins)",
                    destinationNodeId = "return_town",
                    condition = TextGameCondition(forbiddenFlag = "produce_sold", minimumHarvest = 1),
                    effects = listOf(TextGameEffect(harvestDelta = -1, coinsDelta = 3, setFlag = "produce_sold")),
                ),
                TextGameChoice(
                    id = "buy_coat",
                    label = "I reinforce my Summoner coat — 5 coins, 2 materials (+4 health)",
                    destinationNodeId = "final_home",
                    condition = TextGameCondition(requiredFlag = "produce_sold", minimumCoins = 5, minimumMaterials = 2),
                    effects = listOf(TextGameEffect(coinsDelta = -5, materialsDelta = -2, maxHealthDelta = 4, townLevelDelta = 1, setFlag = "bought_coat")),
                ),
            ),
        ),
        TextGameNode(
            id = "final_home",
            type = TextGameNodeType.Hub,
            title = "A Meal Before the Gate",
            prose = "At Home, I turn the Farm's dish and the House's shelter into a run-start modifier. The final patrol proves that no hub stands apart from combat.",
            sceneMediaId = "adams-haven-locations-adams-haven",
            bundledSceneAssetPath = "images/adams_haven/locations/adams-haven.png",
            choices = listOf(
                TextGameChoice(
                    id = "serve_meal",
                    label = "I share lantern stew (+4 guard, +1 SP for the next battle)",
                    destinationNodeId = "final_home",
                    condition = TextGameCondition(forbiddenFlag = "meal_shared", minimumDishes = 1),
                    effects = listOf(TextGameEffect(dishesDelta = -1, preparedGuardDelta = 4, summonerSpDelta = 1, setFlag = "meal_shared")),
                ),
                TextGameChoice(
                    id = "final_patrol",
                    label = "I lead the prepared patrol",
                    destinationNodeId = "final_battle",
                    condition = TextGameCondition(requiredFlags = listOf("bought_coat", "meal_shared")),
                ),
            ),
        ),
        TextGameNode(
            id = "final_battle",
            type = TextGameNodeType.Battle,
            title = "The Haven Gate",
            prose = "I meet the gatebreaker with a stronger coat, a meal's warmth, and Home's guard already around my formation. Every earlier scene now changes this fight.",
            sceneAssetType = "battle",
            sceneMediaId = "adams-haven-characters-ruinous-maw",
            bundledSceneAssetPath = "images/adams_haven/characters/ruinous-maw.png",
            encounterId = "haven_gate",
            victoryNodeId = "final_reward",
            defeatNodeId = "defeat",
            victoryCoins = 6,
            victorySp = 1,
            victoryFlag = "haven_gate_won",
            victoryEffects = listOf(TextGameEffect(materialsDelta = 2)),
        ),
        TextGameNode(
            id = "final_reward",
            type = TextGameNodeType.Reward,
            title = "The Haven Answers",
            prose = "A final set of cards answers the balanced loop I build. I choose one to carry beyond this prototype chapter.",
            sceneMediaId = "adams-haven-objects-celestium-clone-bodies",
            bundledSceneAssetPath = "images/adams_haven/objects/celestium-clone-bodies.png",
            rewardDestinationNodeId = "chapter_complete",
        ),
        TextGameNode(
            id = "chapter_complete",
            type = TextGameNodeType.Ending,
            title = "Two Cards Against the Dark",
            prose = "Silverwood quiets behind me. Battle feeds Farm and Town, Farm feeds Home, and Home prepares my next battle. Three permanent cards now answer my case.",
            sceneMediaId = "adams-haven-locations-elysium-vale",
            bundledSceneAssetPath = "images/adams_haven/locations/elysium-vale.png",
        ),
        TextGameNode(
            id = "defeat",
            type = TextGameNodeType.Ending,
            title = "The Lantern Goes Dark",
            prose = "My case pulls me back to the shack before the road can keep me. I can restart and change my targets, cards, preparation, or turn timing.",
            sceneMediaId = "adams-haven-locations-adams-haven",
            bundledSceneAssetPath = "images/adams_haven/locations/adams-haven.png",
        ),
    ),
    cards = listOf(
        TextGameCard(
            id = "flame_cut", title = "Flame Cut", ownerId = "kestrel", ownerName = "Kaela Stormfang",
            description = "Deal 7 damage. Consumes Gale Mark for +3 damage.", apCost = 1, epCost = 3, damage = 7,
        ),
        TextGameCard(
            id = "gale_mark", title = "Gale Mark", ownerId = "sable", ownerName = "Ghislaine Dedoldia",
            description = "Mark the selected enemy. The next damaging card gains +3 damage.", apCost = 1, epCost = 1, markBonus = 3,
        ),
        TextGameCard(
            id = "transfer", title = "Transfer", ownerId = "sable", ownerName = "Ghislaine Dedoldia",
            description = "Move 2 EP into Kaela's reserve.", apCost = 1, epCost = 2, transferEp = 2, transferTargetId = "kestrel",
        ),
        TextGameCard(
            id = "haven_guard", title = "Haven Guard", ownerId = "kestrel", ownerName = "Card Case",
            description = "Spend 1 Summoner SP to deal 6 damage without consuming AP or EP.", spCost = 1, damage = 6,
        ),
        TextGameCard(
            id = "linnet_wave", title = "Tidal Mend", ownerId = "linnet", ownerName = "Helda Frostmane",
            description = "Deal 4 water damage to the selected enemy.", apCost = 1, epCost = 2, damage = 4,
        ),
        TextGameCard(
            id = "rotfang_maw", title = "Vellum Rend", ownerId = "rotfang", ownerName = "Elara Vellum",
            description = "Deal 6 earth damage to the selected enemy.", apCost = 1, epCost = 3, damage = 6,
        ),
        TextGameCard(
            id = "deadeye_bolt", title = "Storm Bolt", ownerId = "deadeye", ownerName = "Lyra Thornbrook",
            description = "Deal 5 lightning damage to the selected enemy.", apCost = 1, epCost = 2, damage = 5,
        ),
        TextGameCard(
            id = "hexweaver_chorus", title = "Blood Chorus", ownerId = "hexweaver", ownerName = "Amara, the Alluring Empress",
            description = "Deal 5 fire damage to the selected enemy.", apCost = 1, epCost = 2, damage = 5,
        ),
    ),
    collectibleCards = adamsHavenCardCatalog(),
    sceneAssets = adamsHavenSceneCatalog(),
    encounters = listOf(
        TextGameEncounter(
            id = "first_encounter",
            enemies = listOf(
                TextGameEnemy("warden", "Warden", 10, "Black Lantern — 3 damage", 3),
                TextGameEnemy("stinger", "Stinger", 5, "Needle Mend — 2 damage", 2),
            ),
            openingHand = listOf("flame_cut", "gale_mark", "transfer"),
            actorResources = listOf(
                TextGameActorResource("kestrel", "Kaela Stormfang", ap = 1, ep = 3, maxAp = 1, maxEp = 5),
                TextGameActorResource("sable", "Ghislaine Dedoldia", ap = 1, ep = 3, maxAp = 1, maxEp = 5),
            ),
        ),
        TextGameEncounter(
            id = "silverwood_contract",
            enemies = listOf(
                TextGameEnemy("glassroot_sentinel", "Glassroot Sentinel", 12, "Root Bind — 3 damage", 3),
                TextGameEnemy("maw_spawn", "Maw Spawn", 8, "Ruinous Bite — 4 damage", 4),
            ),
            openingHand = listOf("flame_cut", "gale_mark", "transfer", "haven_guard", "linnet_wave", "rotfang_maw", "deadeye_bolt", "hexweaver_chorus"),
            actorResources = listOf(
                TextGameActorResource("kestrel", "Kaela Stormfang", ap = 1, ep = 3, maxAp = 1, maxEp = 5),
                TextGameActorResource("sable", "Ghislaine Dedoldia", ap = 1, ep = 3, maxAp = 1, maxEp = 5),
                TextGameActorResource("linnet", "Helda Frostmane", ap = 1, ep = 3, maxAp = 1, maxEp = 5),
                TextGameActorResource("rotfang", "Elara Vellum", ap = 1, ep = 3, maxAp = 1, maxEp = 5),
            ),
        ),
        TextGameEncounter(
            id = "haven_gate",
            enemies = listOf(
                TextGameEnemy("gatebreaker", "Glassroot Gatebreaker", 18, "Siege Pulse — 5 damage", 5),
            ),
            openingHand = listOf("flame_cut", "gale_mark", "transfer", "haven_guard", "linnet_wave", "rotfang_maw"),
            actorResources = listOf(
                TextGameActorResource("kestrel", "Kaela Stormfang", ap = 1, ep = 3, maxAp = 1, maxEp = 5),
                TextGameActorResource("sable", "Ghislaine Dedoldia", ap = 1, ep = 3, maxAp = 1, maxEp = 5),
                TextGameActorResource("linnet", "Helda Frostmane", ap = 1, ep = 3, maxAp = 1, maxEp = 5),
                TextGameActorResource("rotfang", "Elara Vellum", ap = 1, ep = 3, maxAp = 1, maxEp = 5),
            ),
        ),
    ),
    rewardCardIds = adamsHavenCardCatalog()
        .filter { it.category == "characters" }
        .map { it.id },
    roster = listOf(
        TextGameRosterMember("kestrel", "Kaela Stormfang", "Melee", "Tutorial", "characters/kaela-stormfang"),
        TextGameRosterMember("sable", "Ghislaine Dedoldia", "Ranged", "Tutorial", "characters/ghislaine-dedoldia"),
        TextGameRosterMember("linnet", "Helda Frostmane", "Support", collectibleCardId = "characters/helda-frostmane"),
        TextGameRosterMember("rotfang", "Elara Vellum", "Caster", collectibleCardId = "characters/elara-vellum"),
        TextGameRosterMember("deadeye", "Lyra Thornbrook", "Sniper", collectibleCardId = "characters/lyra-thornbrook"),
        TextGameRosterMember("hexweaver", "Amara, the Alluring Empress", "Caster", collectibleCardId = "characters/amara-the-alluring-empress"),
    ),
    gachaPoolIds = listOf("linnet", "rotfang", "deadeye", "hexweaver"),
    services = listOf(
        TextGameServiceDefinition("rest", "Rest", "House", 1, 70, 1),
        TextGameServiceDefinition("storage", "Storage", "House", 2, 70, 20),
        TextGameServiceDefinition("kitchen", "Kitchen", "House", 3, 70, 1),
        TextGameServiceDefinition("house-deck-hall", "Deck Hall", "House", 4, 60, 1),
        TextGameServiceDefinition("house-guild", "Guild Hall", "House", 5, 50, 1),
        TextGameServiceDefinition("town-deck-hall", "Deck Hall", "Town", 2, 100, 3, "Deck Hall employee: one free card refresh per visit."),
        TextGameServiceDefinition("town-market", "Market", "Town", 2, 100, 6, "Market employee: better sale prices."),
        TextGameServiceDefinition("town-guild", "Guild Hall", "Town", 3, 100, 4, "Guild employee: improved recruitment odds."),
        TextGameServiceDefinition("town-blacksmith", "Blacksmith", "Town", 4, 100, 3, "Blacksmith employee: stronger equipment buffs."),
    ),
)

private fun choice(
    id: String,
    label: String,
    destination: String,
    flag: String,
    companion: String? = null,
) = TextGameChoice(
    id = id,
    label = label,
    destinationNodeId = destination,
    effects = listOf(TextGameEffect(setFlag = flag, companionId = companion)),
)
