package com.ihy2ln.weaverse.core.manga

/** WeaverVerse vocabulary, not fabricated website IDs or claims that a source has these tags. */
object MediaTagCatalog {
    data class Group(val name: String, val tags: List<String>)
    private fun group(name: String, values: String) = Group(name, values.split('|').map(String::trim).filter(String::isNotEmpty))
    val groups = listOf(
        group("Genres", "Action|Adventure|Comedy|Drama|Fantasy|Romance|Sci-Fi|Slice of Life|Mystery|Horror|Thriller|Suspense|Psychological|Historical|Supernatural|Sports|Martial Arts|Mecha|Music|Medical|Crime|Tragedy|Philosophical|Superhero|Isekai|Magical Girls|Gourmet|Political|War|Western|Satire|Parody|Dark Comedy|Romantic Comedy|Coming of Age|Family Drama|Melodrama|Literary Fiction|Historical Fiction|Speculative Fiction|Urban Fantasy|Dark Fantasy|High Fantasy|Low Fantasy|Epic Fantasy|Science Fantasy|Space Opera|Cyberpunk|Steampunk|Dieselpunk|Solarpunk|Biopunk|Post-Apocalyptic|Dystopian|Utopian|Military Sci-Fi|Hard Sci-Fi|Soft Sci-Fi|Cosmic Horror|Folk Horror|Gothic Horror|Body Horror|Survival Horror|Supernatural Horror|Detective Fiction|Noir|Cozy Mystery|Legal Thriller|Political Thriller|Espionage|Heist|Disaster|Survival|Wuxia|Xianxia|Xuanhuan|Murim|LitRPG|GameLit|Progression Fantasy|Portal Fantasy|Historical Fantasy|Mythic Fantasy|Fairy Tale|Fable|Magical Realism|Absurdist|Surrealism|Avant Garde|Experimental|Educational|Documentary|Biography|Autobiography|Memoir|Nonfiction|Travelogue|Poetry|Anthology|Boys Love|Girls Love|Harem|Reverse Harem|Ecchi|Mature|Adult|Erotica|Smut|Hentai"),
        group("Type & format", "Manga|Manhwa|Manhua|Comic|Web Comic|Webtoon|Graphic Novel|Novel|Light Novel|Web Novel|Visual Novel|Anime|Animation|Film|Television|Audio Drama|Podcast|Game|Interactive Fiction|OEL|One Shot|4-Koma|Full Color|Long Strip|Black and White|Partially Colored|Silent Manga|Wordless|Doujinshi|Digital Comic|Motion Comic|Short Story|Novella|Serial|Collected Edition|Omnibus|Artbook|Picture Book|Children's Book|Screenplay|Stage Play|Musical|Stop Motion|CG Animation|Hand-Drawn Animation|Live Action|Original Work|Adaptation|Award Winning|Anthology Series|Episodic|Single Volume|Multi-Volume|Vertical Scroll"),
        group("Demographic", "Shounen|Shoujo|Seinen|Josei|Kodomo|All Ages|Young Adult|New Adult|Adult Audience|Family Friendly"),
        group("Adaptations & connections", "Based on a Web Novel|Based on a Novel|Based on a Light Novel|Based on a Manga|Based on a Manhwa|Based on a Manhua|Based on a Comic|Based on an Anime|Based on a Game|Based on a Visual Novel|Based on a Film|Based on a TV Series|Based on a Myth|Based on a Fairy Tale|Based on Real Events|Adapted to Anime|Adapted to Manga|Adapted to Film|Adapted to Live Action|Adapted to Game|Adapted to Drama|Spin-Off|Sequel|Prequel|Reboot|Remake|Retelling|Crossover|Shared Universe|Alternate Universe|Side Story|Fan Fiction|Public Domain"),
        group("Lead & cast", "Female Lead|Male Lead|Female Protagonist|Male Protagonist|Nonbinary Protagonist|Dual Protagonists|Multiple Protagonists|Ensemble Cast|Primarily Adult Cast|Primarily Female Cast|Primarily Male Cast|Adult Protagonist|Older Protagonist|Child Protagonist|Teenage Protagonist|Animal Protagonist|Nonhuman Protagonist|Monster Protagonist|Villain Protagonist|Unreliable Narrator|Silent Protagonist|Nameless Protagonist|Ordinary Protagonist|Overpowered Protagonist|Weak to Strong|Strong to Stronger|Genius Protagonist|Strategist Protagonist|Reluctant Hero|Chosen One|Anti-Hero|Anti-Villain|Heroine|Villainess|Redeemed Villain|Fallen Hero|Mentor|Rival|Sidekick|Mascot|Found Family|Female Empowerment"),
        group("Character archetypes", "Tsundere|Yandere|Kuudere|Dandere|Deredere|Genki Girl|Genki Guy|Tomboy|Gyaru|Otaku|Chuunibyou|Ojou-sama|Delinquent|Class Representative|Student Council President|Transfer Student|Bookworm|Shut-In|NEET|Idol|Childhood Friend|Prince|Princess|King|Queen|Emperor|Empress|Noble|Commoner|Knight|Paladin|Hero|Demon Lord|Saint|Saintess|Witch|Wizard|Mage|Sorcerer|Necromancer|Alchemist|Summoner|Healer|Bard|Ranger|Rogue|Assassin|Samurai|Ninja|Monk|Priest|Shrine Maiden|Exorcist|Detective|Thief|Pirate|Mercenary|Bounty Hunter|Adventurer|Explorer|Hunter|Monster Hunter|Cultivator|Conqueror|Revolutionary|Rebel|Outcast|Prodigy|Trickster|Mad Scientist|Inventor|Artificial Intelligence"),
        group("Personality & growth", "Shy Protagonist|Confident Protagonist|Ruthless Protagonist|Kind Protagonist|Clever Protagonist|Scheming Protagonist|Naive Protagonist|Stoic Protagonist|Lazy Protagonist|Hardworking Protagonist|Clumsy Character|Cowardly Character|Brave Character|Pacifist|Idealist|Cynic|Perfectionist|Workaholic|Low Self-Esteem|Self-Discovery|Self-Acceptance|Personal Growth|Redemption|Atonement|Corruption|Loss of Innocence|Overcoming Fear|Facing Trauma|Learning Empathy|Moral Ambiguity|Identity Crisis|Hidden Identity|Secret Identity|Double Life|Mistaken Identity|Amnesia|Memory Loss|Memory Recovery|Split Personality|Disguise|Transformation|Body Swap|Gender Swap|Crossdressing|Androgynous Character|Disability|Chronic Illness|Neurodiversity|Deaf Character|Blind Character|Prosthetics|Scars|Glasses|Heterochromia"),
        group("Relationships", "Childhood Friends|Friends to Lovers|Enemies to Lovers|Rivals to Lovers|Strangers to Lovers|Lovers to Enemies|Second Chance Romance|Slow Burn|Love at First Sight|Unrequited Love|Mutual Pining|Love Triangle|Forbidden Love|Secret Relationship|Fake Relationship|Contract Marriage|Arranged Marriage|Marriage of Convenience|Political Marriage|Engagement|Wedding|Married Couple|Divorce|Widowhood|Long-Distance Relationship|Office Romance|School Romance|College Romance|Adult Romance|Age Gap|Interracial Relationship|Interspecies Romance|Class Difference|Status Difference|Royal Romance|Celebrity Romance|Love Rival|Matchmaking|Blind Date|Dating|First Love|First Kiss|Confession|Breakup|Reconciliation|Jealousy|Misunderstanding|Communication|Trust|Betrayal|Loyalty|Friendship|Platonic Love|Bromance|Sisterhood|Queerplatonic Relationship|LGBTQ+|Heterosexual|Gay|Lesbian|Bisexual|Asexual|Transgender|Nonbinary|Polyamory|Healthy Relationship|Toxic Relationship|Abusive Relationship"),
        group("Family & everyday life", "Family Life|Parenthood|Single Parent|Motherhood|Fatherhood|Childcare|Adoption|Foster Family|Blended Family|Siblings|Twins|Triplets|Sibling Rivalry|Parent-Child Relationship|Grandparents|Multigenerational Family|Orphan|Estranged Family|Family Reunion|Family Secrets|Inheritance|Succession|Domestic Life|Cohabitation|Roommates|Neighbors|Housekeeping|Cooking|Baking|Gardening|Pets|Work-Life Balance|Financial Hardship|Debt|Poverty|Wealth|Poor to Rich|Rich to Poor|Homelessness|Retirement|Moving House|Rural Life|City Life|Small Town Life|Community|Festival|Holiday|Vacation|Hot Springs|Camping|Road Trip|Travel|Slice of Work"),
        group("School & education", "School|School Life|High School|Middle School|Elementary School|University|College|Academy|Boarding School|Magic Academy|Military Academy|All-Girls School|All-Boys School|Coeducation|School Club|Literature Club|Art Club|Music Club|Drama Club|Science Club|Sports Club|Student Council|School Festival|Cultural Festival|Sports Festival|School Trip|Exams|Entrance Exams|Graduation|Tutoring|Teaching|Mentorship|Apprenticeship|Research|Scholarship|Academic Rivalry|Bullying|School Discipline|After-School Activities|Study Group|Exchange Student|Language Learning|Homeschooling|Adult Education|Vocational School"),
        group("Work & professions", "Workplace|Office Workers|Business|Corporate Life|Startup|Entrepreneurship|Management|Commerce|Merchant|Shopkeeping|Retail|Restaurant|Cafe|Bakery|Hotel|Hospitality|Farming|Agriculture|Fishing|Forestry|Mining|Construction|Architecture|Engineering|Software Development|Game Development|Web Development|Hacking|Cybersecurity|Journalism|Publishing|Editing|Writing|Translation|Library|Museum|Archaeology|History|Law|Courtroom|Lawyer|Judge|Police|Firefighter|Paramedic|Nursing|Doctor|Surgeon|Veterinarian|Psychologist|Therapist|Teacher|Scientist|Astronaut|Pilot|Sailor|Soldier|Diplomat|Politician|Civil Servant|Housekeeper|Butler|Maid|Bodyguard|Driver|Courier|Freelancer|Gig Work|Job Hunting|Unemployment|Overwork|Labor Rights"),
        group("Arts & entertainment", "Music|Singing|Dancing|Ballet|Theater|Musical Theater|Acting|Voice Acting|Filmmaking|Animation Production|Photography|Painting|Drawing|Sculpture|Pottery|Calligraphy|Handicrafts|Arts and Crafts|Fashion|Modeling|Cosplay|Beauty|Makeover|Design|Comedy Performance|Stand-Up Comedy|Rakugo|Circus|Magic Show|Talent Show|Reality TV|Competition Show|Entertainment Industry|Celebrity|Fandom|Fan Culture|Idol Group|Boy Band|Girl Band|Rock Band|Orchestra|Choir|Classical Music|Jazz|Rock Music|Pop Music|Hip Hop|Electronic Music|Folk Music|Traditional Music|Street Dance|Ballroom Dance|Livestreaming|VTuber|Content Creation|Social Media|Internet Culture|Radio|Broadcasting"),
        group("Sports & games", "Baseball|Basketball|Football|Soccer|Volleyball|Tennis|Table Tennis|Badminton|Golf|Rugby|American Football|Cricket|Hockey|Ice Hockey|Swimming|Diving|Water Polo|Surfing|Sailing|Rowing|Fishing Sport|Running|Track and Field|Marathon|Cycling|Mountain Biking|Motorsport|Car Racing|Motorcycle Racing|Horse Racing|Equestrian|Gymnastics|Figure Skating|Speed Skating|Skiing|Snowboarding|Skateboarding|Parkour|Rock Climbing|Mountain Climbing|Hiking|Weightlifting|Bodybuilding|Cheerleading|Archery|Shooting Sports|Boxing|Kickboxing|Wrestling|Sumo|Judo|Karate|Kendo|Taekwondo|Kung Fu|Mixed Martial Arts|Fencing|Chess|Shogi|Go|Mahjong|Poker|Card Games|Board Games|Tabletop RPG|Video Games|Esports|Arcade Games|Rhythm Games|Strategy Games|Puzzle Games|Competitive Gaming|Team Sports|Individual Sports|Sports Tournament|Underdog Team|Training Camp|Coach"),
        group("Fantasy & powers", "Magic|Elemental Magic|Healing Magic|Necromancy|Summoning|Alchemy|Enchanting|Divination|Illusion|Transformation Magic|Time Magic|Space Magic|Blood Magic|Forbidden Magic|Spirit Magic|Runes|Spells|Rituals|Curses|Blessings|Prophecy|Destiny|Mana|Qi|Cultivation|Immortality|Ascension|Reincarnation|Transmigration|Regression|Resurrection|Rebirth|Possession|Soul Transfer|Soulmates|Spiritual Power|Psychic Powers|Telepathy|Telekinesis|Clairvoyance|Mind Reading|Mind Control|Super Strength|Super Speed|Flight|Invisibility|Shapeshifting|Size Changing|Healing Factor|Invulnerability|Teleportation|Time Stop|Time Loop|Time Travel|Alternate Timelines|Parallel Worlds|Multiverse|Portal|Dungeon|Dungeon Core|Dungeon Exploring|Tower Climbing|Monster Taming|Familiar|Magic Contract|Magic Artifact|Legendary Weapon|Cursed Weapon|Sentient Weapon|Skill Acquisition|Power Copying|Power Sealing|Power Awakening|Secret Power|Overpowered|Weak to Strong|Leveling|System|Status Window|Skill Tree|Quest|Class System|Job Change|Cheat Ability|Inventory|Crafting|Loot|Raid|Boss Battle|Guild|Adventurers Guild|Party|Kingdom Building|Nation Building|Territory Management|Sect Building"),
        group("Creatures & beings", "Demons|Angels|Gods|Goddesses|Deities|Spirits|Ghosts|Undead|Zombies|Vampires|Werewolves|Shapeshifters|Dragons|Wyverns|Phoenix|Griffin|Unicorn|Pegasus|Mermaids|Sirens|Fairies|Elves|Dark Elves|Dwarves|Orcs|Goblins|Ogres|Trolls|Giants|Titans|Centaurs|Minotaurs|Gorgons|Harpies|Kitsune|Tanuki|Oni|Tengu|Yokai|Yuki Onna|Bakeneko|Kappa|Jiangshi|Jinn|Golem|Homunculus|Slime|Mimic|Skeleton|Lich|Reaper|Chimera|Kaiju|Monster Girls|Monster Boys|Beastfolk|Anthropomorphic Animals|Kemonomimi|Nekomimi|Fox Girls|Fox Boys|Talking Animals|Sentient Plants|Artificial Life|Robots|Androids|Cyborgs|Aliens|Extraterrestrial Civilization|Hive Mind|Eldritch Beings|Lovecraftian Monsters|Cryptids|Sea Monsters|Dinosaurs|Prehistoric Animals|Insects|Cats|Dogs|Birds|Wolves|Horses"),
        group("Science & technology", "Space Exploration|Space Travel|Interstellar Travel|First Contact|Alien Invasion|Space Colony|Space Station|Generation Ship|Terraforming|Faster Than Light|Spaceship|Space Battle|Robotics|Artificial Intelligence|Machine Learning|Virtual Reality|Augmented Reality|Simulated World|Cybernetics|Genetic Engineering|Cloning|Biotechnology|Nanotechnology|Mind Uploading|Digital Consciousness|Transhumanism|Posthumanism|Scientific Discovery|Time Machine|Alternate History|Future Technology|Ancient Technology|Lost Technology|Technology vs Magic|Technological Singularity|Drones|Exoskeleton|Powered Armor|Giant Robot|Real Robot|Super Robot|Space Mecha|Invention|Industrial Revolution|Renewable Energy|Environmental Science|Ecology|Climate Change|Pandemic|Space Western|Cybercrime|Surveillance|Dystopian Technology"),
        group("World & setting", "Japan|Korea|China|Taiwan|Hong Kong|India|Southeast Asia|Middle East|Africa|Europe|North America|South America|Australia|Pacific Islands|Arctic|Antarctica|Ancient World|Prehistory|Ancient Egypt|Ancient Greece|Ancient Rome|Medieval|Renaissance|Victorian Era|Edo Period|Sengoku Period|Meiji Era|Taisho Era|Showa Era|Joseon Era|Three Kingdoms|19th Century|20th Century|21st Century|Near Future|Far Future|Modern Day|Historical Setting|Fantasy World|Otherworld|Underworld|Heaven|Hell|Dream World|Digital World|Ocean|Underwater|Desert|Jungle|Forest|Mountains|Island|Remote Village|Metropolis|Suburbs|Countryside|Castle|Palace|Mansion|Temple|Shrine|Monastery|Hospital|Prison|Battlefield|Ruins|Labyrinth|Underground City|Floating Island|Sky City|Wasteland|Space|Solar System|Moon|Mars|Distant Planet|Frontier|Borderlands|Walled City|Secret Base|Abandoned Building"),
        group("Society & conflict", "Royalty|Nobility|Aristocracy|Feudalism|Monarchy|Empire|Republic|Democracy|Dictatorship|Theocracy|Oligarchy|Politics|Political Intrigue|Court Intrigue|Succession War|Civil War|World War|Cold War|Revolution|Rebellion|Resistance|Colonialism|Imperialism|Nationalism|Class Conflict|Social Inequality|Discrimination|Racism|Sexism|Prejudice|Immigration|Refugees|Diaspora|Cultural Identity|Culture Clash|Religion|Faith|Atheism|Mythology|Folklore|Secret Society|Cult|Conspiracy|Corruption|Propaganda|Censorship|Freedom|Justice|Human Rights|Labor Movement|Environmentalism|Conservation|Capitalism|Communism|Socialism|Economics|Trade|Diplomacy|International Conflict|Peace Negotiation|War Crimes|Military|Strategy|Tactics|Siege|Naval Warfare|Aerial Warfare|Guerrilla Warfare|Arms Race|Disarmament"),
        group("Plot & narrative", "Revenge|Rescue Mission|Escape|Pursuit|Investigation|Murder Mystery|Locked-Room Mystery|Whodunit|Howdunit|Missing Person|Treasure Hunt|Expedition|Journey|Pilgrimage|Homecoming|Fish Out of Water|Rags to Riches|Fall from Grace|Hero's Journey|Quest for Identity|Quest for Power|Quest for Immortality|Forbidden Knowledge|Deal with the Devil|Faustian Bargain|Wish Fulfillment|Monkey's Paw|Butterfly Effect|Time Paradox|Predestination|Second Chance|New Game Plus|Otome Game|Trapped in a Game|Transported to Another World|Return from Another World|Reverse Isekai|Summoned Hero|Reincarnated as a Monster|Reincarnated as a Villainess|Reincarnated as Royalty|Regression to Childhood|Knowledge of the Future|Secret Past|Hidden Lineage|Lost Heir|Switched at Birth|Doppelganger|Impostor|Undercover|Infiltration|Sabotage|Heist Planning|Prison Break|Battle Royale|Death Game|Survival Game|Tournament Arc|Training Arc|Time Skip|Flashback|Nonlinear Narrative|Multiple Timelines|Multiple Perspectives|Framing Narrative|Story Within a Story|Metafiction|Fourth Wall|Unreliable Memory|Open Ending|Happy Ending|Bittersweet Ending|Tragic Ending|Plot Twist|Cliffhanger|Slow Pace|Fast Pace|Character Driven|Plot Driven|Worldbuilding"),
        group("Mood & themes", "Wholesome|Heartwarming|Healing|Iyashikei|Cozy|Relaxing|Feel-Good|Cute|Cute Girls Doing Cute Things|Cute Boys Doing Cute Things|Lighthearted|Hopeful|Optimistic|Inspirational|Motivational|Melancholic|Bittersweet|Tragic|Bleak|Grimdark|Gritty|Suspenseful|Atmospheric|Dreamlike|Surreal|Absurd|Comedic|Silly|Serious|Emotional|Poignant|Nostalgic|Loneliness|Isolation|Belonging|Acceptance|Forgiveness|Grief|Loss|Death|Mortality|Life After Death|Existentialism|Nihilism|Meaning of Life|Free Will|Determinism|Nature vs Nurture|Good vs Evil|Order vs Chaos|Tradition vs Progress|Humanity vs Nature|Humanity vs Technology|Man vs Society|Man vs Self|Coming Out|Healing from Trauma|Mental Health|Depression|Anxiety|Addiction|Recovery|Resilience|Hope|Despair|Sacrifice|Duty|Honor|Ambition|Greed|Pride|Envy|Compassion|Empathy|Courage|Perseverance|Teamwork|Cooperation|Competition|Reconciliation|Spiritual Journey"),
        group("Content notices", "Violence|Graphic Violence|Gore|Blood|Murder|Mass Murder|War Violence|Domestic Violence|Child Abuse|Animal Cruelty|Torture|Kidnapping|Slavery|Human Trafficking|Bullying|Self-Harm|Suicide|Substance Abuse|Drug Use|Alcohol|Smoking|Gambling|Strong Language|Nudity|Sexual Content|Sexual Violence|Coercion|Harassment|Death of a Parent|Death of a Child|Terminal Illness|Body Image|Eating Disorders|Pregnancy|Miscarriage|Bereavement|Psychological Abuse|Emotional Abuse|Manipulation|Gaslighting|Stalking|Obsession|Cannibalism|Body Modification"),
    )
    val all: List<String> = groups.flatMap { it.tags }.distinctBy(CatalogTags::normalize)
    val genres: List<String> = groups.first().tags
    /** Actual metadata labels stay visible, even when they have an alias in the curated vocabulary. */
    fun options(sourceTags: List<String>, selected: String = ""): List<String> =
        (sourceTags + selected.split(',').map { it.trim().removePrefix("!") } + all)
            .filter(String::isNotBlank).distinctBy(CatalogTags::normalize).sortedBy { it.lowercase() }

    fun search(options: List<String>, query: String): List<String> {
        val terms = query.trim().split(Regex("\\s+")).filter(String::isNotBlank).map(CatalogTags::normalize)
        val phrase = CatalogTags.normalize(query)
        return options.filter { tag -> phrase in CatalogTags.normalize(tag) || terms.all { it in CatalogTags.normalize(tag) } }
    }
}
